### ISSUE TITLE
Can I embed and modify this project within segmentio/terraform-docs

### ISSUE THREAD

**Issue by khos2ow** [hashicorp/terraform-config-inspect#42]
We are currently trying to fix segmentio/terraform-docs#176 which internally would have depended on #24 but since `terraform-config-inspect` is considered to be feature-complete and it appears #24 is stalled and will not get merged, we've decided to move `github.com/hashicorp/terraform-config-inspect` as an internal package (`github.com/segmentio/terraform-docs/internal/tfconfig`) rather than it being an external vendor dependency and apply the changes in #24 directly in there (the change is done in https://github.com/segmentio/terraform-docs/pull/221).

I want to double check that we would be able to do this in-project fork and modification considering the license `terraform-config-inspect` is being released under. I've read the [MPL-2.0 LICENSE](https://github.com/hashicorp/terraform-config-inspect/blob/master/LICENSE) and I believe we'd be able to do that but I want to be absolutely sure that this would be ok. I'd really appreciate it if you can advise on the matter.

**Comment by khos2ow** [comment]
@radeksimko @mildwonkey ping.

**Comment by paultyng** [comment]
@khos2ow yes you can use a modified fork of the code and distribute it with your own work, as long as you meet a few requirements (most notably including the LICENSE/copyright info). See some of the FAQs in more plain language here:

https://www.mozilla.org/en-US/MPL/2.0/FAQ/#distribute-modified-source

**Comment by khos2ow** [comment]
@paultyng that's great, thank you so much for the explanation.

**Comment by khos2ow** [comment]
@paultyng we went ahead with your suggestion and [this](https://github.com/segmentio/terraform-docs/tree/master/internal/tfconfig) is the in-repo fork of the `terraform-config-inspect`. I've included original license file in the folder too ([here](https://github.com/segmentio/terraform-docs/blob/master/internal/tfconfig/LICENSE)). Would you think this is enough or do I need to explicitly mention it somewhere else as well, e.g. our own README or LICENSE?

If everything looked good to you feel free to close this issue, otherwise please let me know.

**Comment by paultyng** [comment]
👍 Looks fine for me as is, but may be helpful to just add a quick pointer to the source somewhere in the README or something.
