### ISSUE TITLE
Feature Request: Support sensitive attribute for outputs

### ISSUE THREAD

**Issue by andy-caruso** [hashicorp/terraform-config-inspect#55]
This will allow developers to properly manage sensitive outputs when displaying them in a system

**Comment by mildwonkey** [comment]
`terraform-config-inspect` is more of a local development tool; can you explain a bit more about how you are using it to display outputs to a system? I would suggest that you use `terraform output` or other terraform-specific commands for user-facing displays instead of `terraform-config-inspect`.

**Comment by andy-caruso** [comment]
A couple of examples:
- A company-wide web catalog of terraform modules could use this feature to more accurately describe the outputs of each module. 
- A security monitoring tool could fire an alert whenever a log message is created that includes a sensitive output to detect erroneous/suspicious actuation of terraform.

In both of the above cases, I think`terraform-config-inspect` is being used as intended to understand the structure of a set of terraform files and not to create/update cloud infrastructure.

**Comment by mildwonkey** [comment]
👍 thanks again @andy-caruso !
