### ISSUE TITLE
'go get ...' install method fails on MacOS/homebrew

### ISSUE THREAD

**Issue by acutchin-bitpusher** [hashicorp/terraform-config-inspect#65]
I am unfamiliar with Go, but the generic installation instructions in README.md don't work on my Macbook:

    # uname -a
    Darwin <snipped> 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

    # brew info go
    go: stable 1.17, HEAD
    ...
      Built from source on 2021-09-01 at 14:39:49
    ...

    # which go
    /Users/<snipped>/homebrew/bin/go

    # go version
    go version go1.17 darwin/amd64

    # go get github.com/hashicorp/terraform-config-inspect
    go get: installing executables with 'go get' in module mode is deprecated.
      Use 'go install pkg@version' instead.
      For more information, see https://golang.org/doc/go-get-install-deprecation
      or run 'go help get' or 'go help install'.

**Comment by DavidGamba** [comment]
```
$ go install github.com/hashicorp/terraform-config-inspect@latest
```

**Comment by AbbyDeng** [comment]
i can open a PR on [README.md](https://github.com/hashicorp/terraform-config-inspect#readme)
